### ISSUE TITLE
gst_query_set_latency assert

### ISSUE THREAD

**Issue by stefanalund** [EricssonResearch/openwebrtc#183]
Probably not an issue but still something to fix perhaps:
```
(<unknown>:1008): GStreamer-CRITICAL **: gst_query_set_latency: assertion 'GST_CLOCK_TIME_IS_VALID (min_latency)' failed
```

**Comment by sdroege** [comment]
Definitely something to fix, yes. When did that happen, what did you do?

Do you have a debug log?

**Comment by sdroege** [comment]
Or a backtrace of the warning, e.g. after setting G_DEBUG=fatal_warnings :)

**Comment by sdroege** [comment]
Most likely comes from avfvideosrc, the latency code there looks like it could run into that warning.

**Comment by sdroege** [comment]
This can also cause the black frames BTW, will fix tomorrow

**Comment by sdroege** [comment]
This should be fixed now: http://cgit.freedesktop.org/gstreamer/gst-plugins-bad/commit/?id=84ab11afdbfd87bf1aa916cc7803163536513339

**Comment by sdroege** [comment]
And a couple of related fixes in all GStreamer modules

**Comment by stefanalund** [comment]
This "problem" is still present, even if the (H.264) video is now working: https://github.com/EricssonResearch/openwebrtc/issues/184

**Comment by sdroege** [comment]
Can you give me a debug log and a backtrace of the warning (with G_DEBUG=fatal_warnings)?

**Comment by superdump** [comment]
@stefanalund ?

**Comment by stefanalund** [comment]
Not sure what we are looking for here. If I enable G_DEBUG=fatal_warnings I get a SIGTRAP, where:

```
(lldb) bt all
* thread #1: tid = 0x160efa, 0x346ce4f0 libsystem_kernel.dylib`mach_msg_trap + 20, queue = 'com.apple.main-thread', stop reason = signal SIGTRAP
  * frame #0: 0x346ce4f0 libsystem_kernel.dylib`mach_msg_trap + 20
    frame #1: 0x346ce2e8 libsystem_kernel.dylib`mach_msg + 40
    frame #2: 0x2684231a CoreFoundation`__CFRunLoopServiceMachPort + 146
    frame #3: 0x268408c0 CoreFoundation`__CFRunLoopRun + 1016
    frame #4: 0x2678e3c0 CoreFoundation`CFRunLoopRunSpecific + 476
    frame #5: 0x2678e1d2 CoreFoundation`CFRunLoopRunInMode + 106
    frame #6: 0x2db460a8 GraphicsServices`GSEventRunModal + 136
    frame #7: 0x29d9c7b0 UIKit`UIApplicationMain + 1440
    frame #8: 0x0003f8dc SimpleDemo`main(argc=1, argv=0x013bba98) + 116 at main.m:14

  thread #3: tid = 0x160f14, 0x346e29cc libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #0: 0x346e29cc libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x3475ceac libsystem_pthread.dylib`_pthread_wqthread + 792

  thread #4: tid = 0x160f15, 0x346e29cc libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #0: 0x346e29cc libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x3475ceac libsystem_pthread.dylib`_pthread_wqthread + 792

  thread #5: tid = 0x160f17, 0x346ce2a0 libsystem_kernel.dylib`kevent64 + 24, queue = 'com.apple.libdispatch-manager'
    frame #0: 0x346ce2a0 libsystem_kernel.dylib`kevent64 + 24
    frame #1: 0x01625678 libdispatch.dylib`_dispatch_mgr_invoke + 280
    frame #2: 0x0161a49a libdispatch.dylib`_dispatch_mgr_thread + 38

  thread #6: tid = 0x160f18, 0x346e219c libsystem_kernel.dylib`__semwait_signal + 24, name = 'gputools.smt_poll.0x1558a0b0'
    frame #0: 0x346e219c libsystem_kernel.dylib`__semwait_signal + 24
    frame #1: 0x34641a70 libsystem_c.dylib`nanosleep + 172
    frame #2: 0x346419c0 libsystem_c.dylib`usleep + 52
    frame #3: 0x01662ff8 GPUToolsCore`smt_poll_thread_entry(void*) + 124
    frame #4: 0x3475ee92 libsystem_pthread.dylib`_pthread_body + 138
    frame #5: 0x3475ee06 libsystem_pthread.dylib`_pthread_start + 118

  thread #7: tid = 0x160f19, 0x346e29cc libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #0: 0x346e29cc libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x3475ceac libsystem_pthread.dylib`_pthread_wqthread + 792

  thread #8: tid = 0x160f25, 0x0023ee6c SimpleDemo`g_slice_free1(mem_size=28, mem_block=0x1619a800) at gslice.c:1076, name = 'owr-bridge-thread'
    frame #0: 0x0023ee6c SimpleDemo`g_slice_free1(mem_size=28, mem_block=0x1619a800) at gslice.c:1076
    frame #1: 0x00284c9e SimpleDemo`array_free(array=<unavailable>, flags=<unavailable>) + 90 at garray.c:379
    frame #2: 0x0039c8e0 SimpleDemo`gst_structure_free(structure=0x15a0e480) + 76 at gststructure.c:386
    frame #3: 0x003778ae SimpleDemo`_gst_query_free(query=0x159f6978) + 26 at gstquery.c:195
    frame #4: 0x003645a6 SimpleDemo`query_latency_default_fold [inlined] gst_query_unref(q=0x159f6978) + 6 at gstquery.h:237
    frame #5: 0x003645a0 SimpleDemo`query_latency_default_fold(item=<unavailable>, ret=<unavailable>, user_data=<unavailable>) + 196 at gstpad.c:3094
    frame #6: 0x00358bfe SimpleDemo`gst_iterator_fold(it=0x159caa78, func=0x003644dd, ret=0x03e6bab4, user_data=0x03e6baa0) + 70 at gstiterator.c:614
    frame #7: 0x0035e98e SimpleDemo`gst_pad_query_default [inlined] gst_pad_query_latency_default(pad=<unavailable>, query=<unavailable>) + 46 at gstpad.c:3121
    frame #8: 0x0035e960 SimpleDemo`gst_pad_query_default(pad=0x15a08768, parent=<unavailable>, query=0x159f69d8) + 576 at gstpad.c:3214
    frame #9: 0x00073d40 SimpleDemo`gst_queue_handle_src_query(pad=0x15a08768, parent=0x1595ea00, query=0x159f69d8) + 68 at gstqueue.c:1393
    frame #10: 0x0035f438 SimpleDemo`gst_pad_query(pad=0x15a08768, query=<unavailable>) + 296 at gstpad.c:3719
    frame #11: 0x0035fc6a SimpleDemo`gst_pad_peer_query(pad=0x15a088a0, query=<unavailable>) + 326 at gstpad.c:3847
    frame #12: 0x003006da SimpleDemo`gst_base_sink_query_latency(sink=0x159b19d8, live=0x03e6bd14, upstream_live=0x03e6bd10, min_latency=0x03e6bd08, max_latency=<unavailable>) + 122 at gstbasesink.c:1077
    frame #13: 0x003089dc SimpleDemo`default_element_query(element=<unavailable>, query=0x159f6528) + 392 at gstbasesink.c:4760
    frame #14: 0x00371088 SimpleDemo`bin_query_latency_fold(vitem=<unavailable>, ret=0x03e6be20, fold=0x03e6be78) + 96 at gstbin.c:3871
    frame #15: 0x00358bfe SimpleDemo`gst_iterator_fold(it=0x159888b8, func=0x00371029, ret=0x03e6be20, user_data=0x03e6be78) + 70 at gstiterator.c:614
    frame #16: 0x003715c6 SimpleDemo`bin_iterate_fold(bin=0x15a04218, iter=0x159888b8, fold_init=0x00370e0d, fold_done=<unavailable>, fold_func=0x00371029, fold_data=0x03e6be78, default_return=1) + 82 at gstbin.c:3950
    frame #17: 0x0036e00c SimpleDemo`gst_bin_query(element=<unavailable>, query=0x159f6528) + 256 at gstbin.c:4061
    frame #18: 0x0036f9b4 SimpleDemo`gst_bin_do_latency_func(bin=0x15a04218) + 88 at gstbin.c:2479
    frame #19: 0x0018b590 SimpleDemo`ffi_call_SYSV + 48
    frame #20: 0x0018d4c2 SimpleDemo`ffi_call(cif=0x03e6bfcc, fn=<unavailable>, rvalue=0x03e6bf9c, avalue=<unavailable>) + 122 at ffi.c:339
    frame #21: 0x002aa216 SimpleDemo`g_cclosure_marshal_generic(closure=0x1576e0f0, return_gvalue=0x03e6c0d0, n_param_values=<unavailable>, param_values=<unavailable>, invocation_hint=0x03e6c0ec, marshal_data=<unavailable>) + 434 at gclosure.c:1448
    frame #22: 0x002a9e5e SimpleDemo`g_type_class_meta_marshal(closure=<unavailable>, return_value=<unavailable>, n_param_values=<unavailable>, param_values=<unavailable>, invocation_hint=<unavailable>, marshal_data=0x00000110) + 50 at gclosure.c:961
    frame #23: 0x002a98fa SimpleDemo`g_closure_invoke(closure=0x1576e0f0, return_value=0x03e6c0d0, n_param_values=1, param_values=0x03e6c13c, invocation_hint=<unavailable>) + 234 at gclosure.c:768
    frame #24: 0x002bcfe8 SimpleDemo`signal_emit_unlocked_R(node=<unavailable>, detail=<unavailable>, instance=<unavailable>, emission_return=<unavailable>, instance_and_params=<unavailable>) + 1344 at gsignal.c:3591
    frame #25: 0x002bd792 SimpleDemo`g_signal_emit_valist(instance=0x15a04218, signal_id=<unavailable>, detail=0, var_args=<unavailable>) + 1238 at gsignal.c:3319
    frame #26: 0x002bdc70 SimpleDemo`g_signal_emit(instance=<unavailable>, signal_id=<unavailable>, detail=<unavailable>) + 20 at gsignal.c:3365
    frame #27: 0x0036bb7c SimpleDemo`gst_bin_recalculate_latency(bin=0x15a04218) + 28 at gstbin.c:2458
    frame #28: 0x0036cc4c SimpleDemo`gst_bin_change_state_func(element=0x15a04218, transition=GST_STATE_CHANGE_PAUSED_TO_PLAYING) + 412 at gstbin.c:2576
    frame #29: 0x00365a3e SimpleDemo`gst_pipeline_change_state(element=0x15a04218, transition=GST_STATE_CHANGE_PAUSED_TO_PLAYING) + 326 at gstpipeline.c:474
    frame #30: 0x003513e0 SimpleDemo`gst_element_change_state(element=0x15a04218, transition=<unavailable>) + 20 at gstelement.c:2602
    frame #31: 0x003514f8 SimpleDemo`gst_element_change_state(element=<unavailable>, transition=<unavailable>) + 300 at gstelement.c:2646
    frame #32: 0x003514f8 SimpleDemo`gst_element_change_state(element=<unavailable>, transition=<unavailable>) + 300 at gstelement.c:2646
    frame #33: 0x0035207e SimpleDemo`gst_element_set_state_func(element=0x15a04218, state=<unavailable>) + 322 at gstelement.c:2558
    frame #34: 0x004675f8 SimpleDemo`owr_local_media_source_request_source(media_source=0x15977ba8, caps=0x159c46e8) + 2472 at owr_local_media_source.c:617
    frame #35: 0x004682dc SimpleDemo`_owr_media_source_request_source(media_source=0x15977ba8, caps=0x159c46e8) + 56 at owr_media_source.c:559
    frame #36: 0x0044ee22 SimpleDemo`maybe_start_renderer(renderer=<unavailable>) + 66 at owr_media_renderer.c:284
    frame #37: 0x0044ed90 SimpleDemo`owr_media_renderer_set_source(renderer=0x159ca600, source=0x15977ba8) + 132 at owr_media_renderer.c:344
    frame #38: 0x0018b590 SimpleDemo`ffi_call_SYSV + 48
    frame #39: 0x0018d4c2 SimpleDemo`ffi_call(cif=0x03e6c5f8, fn=<unavailable>, rvalue=0x03e6c5e8, avalue=<unavailable>) + 122 at ffi.c:339
    frame #40: 0x00226916 SimpleDemo`g_callable_info_invoke(info=<unavailable>, function=0x0044ed0d, in_args=<unavailable>, n_in_args=<unavailable>, out_args=<unavailable>, n_out_args=<unavailable>, return_value=0x03e6c6e4, is_method=<unavailable>, throws=<unavailable>, error=<unavailable>) + 686 at gicallableinfo.c:703
    frame #41: 0x0021cbe8 SimpleDemo`g_function_info_invoke(info=0x161b4280, in_args=0x157bcff0, n_in_args=2, out_args=0x157bd000, n_out_args=<unavailable>, return_value=<unavailable>, error=0x03e6c6e0) + 120 at gifunctioninfo.c:281
    frame #42: 0x004d2ad6 SimpleDemo`seed_gobject_method_invoked(ctx=0x03e6c858, function=<unavailable>, this_object=<unavailable>, argumentCount=1, arguments=<unavailable>, exception=<unavailable>) + 942 at seed-engine.c:707
    frame #43: 0x27c5aac8 JavaScriptCore`JSC::JSCallbackObject<JSC::JSDestructibleObject>::call(JSC::ExecState*) + 420
    frame #44: 0x27a88532 JavaScriptCore`JSC::LLInt::setUpCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*) + 458
    frame #45: 0x27a85a9e JavaScriptCore`llint_slow_path_call + 122
    frame #46: 0x27cb436c JavaScriptCore`llint_entry + 20268
    frame #47: 0x27cb4504 JavaScriptCore`llint_entry + 20676

  thread #9: tid = 0x160f26, 0x346e1b38 libsystem_kernel.dylib`__psynch_cvwait + 24, name = 'JavaScriptCore::BlockFree'
    frame #0: 0x346e1b38 libsystem_kernel.dylib`__psynch_cvwait + 24
    frame #1: 0x3475e3f8 libsystem_pthread.dylib`_pthread_cond_wait + 520
    frame #2: 0x3475f31c libsystem_pthread.dylib`pthread_cond_timedwait + 44
    frame #3: 0x33966f5e libc++.1.dylib`std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1ll, 1000000000ll> > >) + 182
    frame #4: 0x27b73514 JavaScriptCore`std::__1::cv_status std::__1::condition_variable::wait_for<long long, std::__1::ratio<1ll, 1000ll> >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::duration<long long, std::__1::ratio<1ll, 1000ll> > const&) + 196
    frame #5: 0x27a4d07e JavaScriptCore`JSC::BlockAllocator::blockFreeingThreadMain() + 86
    frame #6: 0x27a49596 JavaScriptCore`WTF::wtfThreadEntryPoint(void*) + 14
    frame #7: 0x3475ee92 libsystem_pthread.dylib`_pthread_body + 138
    frame #8: 0x3475ee06 libsystem_pthread.dylib`_pthread_start + 118

  thread #10: tid = 0x160f27, 0x346e1b38 libsystem_kernel.dylib`__psynch_cvwait + 24, name = 'JavaScriptCore::Marking'
    frame #0: 0x346e1b38 libsystem_kernel.dylib`__psynch_cvwait + 24
    frame #1: 0x3475e3f8 libsystem_pthread.dylib`_pthread_cond_wait + 520
    frame #2: 0x3475f2dc libsystem_pthread.dylib`pthread_cond_wait + 40
    frame #3: 0x33966e90 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 36
    frame #4: 0x27c14cb4 JavaScriptCore`JSC::GCThread::waitForNextPhase() + 104
    frame #5: 0x27c14d18 JavaScriptCore`JSC::GCThread::gcThreadMain() + 52
    frame #6: 0x27a49596 JavaScriptCore`WTF::wtfThreadEntryPoint(void*) + 14
    frame #7: 0x3475ee92 libsystem_pthread.dylib`_pthread_body + 138
    frame #8: 0x3475ee06 libsystem_pthread.dylib`_pthread_start + 118

  thread #11: tid = 0x160f28, 0x346ce4f0 libsystem_kernel.dylib`mach_msg_trap + 20, name = 'AVAudioSession Notify Thread'
    frame #0: 0x346ce4f0 libsystem_kernel.dylib`mach_msg_trap + 20
    frame #1: 0x346ce2e8 libsystem_kernel.dylib`mach_msg + 40
    frame #2: 0x2684231a CoreFoundation`__CFRunLoopServiceMachPort + 146
    frame #3: 0x268408c0 CoreFoundation`__CFRunLoopRun + 1016
    frame #4: 0x2678e3c0 CoreFoundation`CFRunLoopRunSpecific + 476
    frame #5: 0x2678e1d2 CoreFoundation`CFRunLoopRunInMode + 106
    frame #6: 0x254983ee libAVFAudio.dylib`GenericRunLoopThread::Entry(void*) + 134
    frame #7: 0x2548a90a libAVFAudio.dylib`CAPThread::Entry(CAPThread*) + 194
    frame #8: 0x3475ee92 libsystem_pthread.dylib`_pthread_body + 138
    frame #9: 0x3475ee06 libsystem_pthread.dylib`_pthread_start + 118

  thread #12: tid = 0x160f2b, 0x346e29cc libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #0: 0x346e29cc libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x3475ceac libsystem_pthread.dylib`_pthread_wqthread + 792

  thread #13: tid = 0x160f53, 0x346e1b38 libsystem_kernel.dylib`__psynch_cvwait + 24, name = 'pool'
    frame #0: 0x346e1b38 libsystem_kernel.dylib`__psynch_cvwait + 24
    frame #1: 0x3475e432 libsystem_pthread.dylib`_pthread_cond_wait + 578
    frame #2: 0x3475e1ec libsystem_pthread.dylib`pthread_cond_timedwait_relative_np + 16
    frame #3: 0x0028d44a SimpleDemo`g_cond_wait_until(cond=<unavailable>, mutex=<unavailable>, end_time=<unavailable>) + 134 at gthread-posix.c:891
    frame #4: 0x0028dd4c SimpleDemo`g_async_queue_pop_intern_unlocked(queue=0x155f8da0, wait=1, end_time=0) + 76 at gasyncqueue.c:422
    frame #5: 0x0023ca22 SimpleDemo`g_thread_pool_thread_proxy [inlined] g_thread_pool_wait_for_new_task + 56 at gthreadpool.c:262
    frame #6: 0x0023c9ea SimpleDemo`g_thread_pool_thread_proxy(data=<unavailable>) + 34 at gthreadpool.c:296
    frame #7: 0x0023fbf6 SimpleDemo`g_thread_proxy(data=0x159f67c8) + 78 at gthread.c:764
    frame #8: 0x3475ee92 libsystem_pthread.dylib`_pthread_body + 138
    frame #9: 0x3475ee06 libsystem_pthread.dylib`_pthread_start + 118

  thread #14: tid = 0x160f62, 0x346e1b38 libsystem_kernel.dylib`__psynch_cvwait + 24, name = 'source-tee-fakesink-queue:src'
    frame #0: 0x346e1b38 libsystem_kernel.dylib`__psynch_cvwait + 24
    frame #1: 0x3475e3f8 libsystem_pthread.dylib`_pthread_cond_wait + 520
    frame #2: 0x3475f2dc libsystem_pthread.dylib`pthread_cond_wait + 40
    frame #3: 0x0028d292 SimpleDemo`g_cond_wait(cond=<unavailable>, mutex=<unavailable>) + 34 at gthread-posix.c:767
    frame #4: 0x00074084 SimpleDemo`gst_queue_loop(pad=<unavailable>) + 484 at gstqueue.c:1299
    frame #5: 0x00372120 SimpleDemo`gst_task_func(task=0x161d1058) + 276 at gsttask.c:331
    frame #6: 0x0023ca40 SimpleDemo`g_thread_pool_thread_proxy(data=<unavailable>) + 120 at gthreadpool.c:307
    frame #7: 0x0023fbf6 SimpleDemo`g_thread_proxy(data=0x159f6ac8) + 78 at gthread.c:764
    frame #8: 0x3475ee92 libsystem_pthread.dylib`_pthread_body + 138
    frame #9: 0x3475ee06 libsystem_pthread.dylib`_pthread_start + 118

  thread #15: tid = 0x160f63, 0x346ce4f0 libsystem_kernel.dylib`mach_msg_trap + 20, name = 'video-source:src', queue = 'com.apple.avfoundation.videocapturedevice.source_queue'
    frame #0: 0x346ce4f0 libsystem_kernel.dylib`mach_msg_trap + 20
    frame #1: 0x346ce2e8 libsystem_kernel.dylib`mach_msg + 40
    frame #2: 0x016259b6 libdispatch.dylib`_dispatch_mach_msg_send + 526
    frame #3: 0x0161b5fc libdispatch.dylib`dispatch_mach_send + 300
    frame #4: 0x34775866 libxpc.dylib`_xpc_connection_send_message_with_reply_f + 98
    frame #5: 0x347757ae libxpc.dylib`xpc_connection_send_message_with_reply_sync + 142
    frame #6: 0x270377b2 CoreMedia`FigXPCRemoteClientSendSyncMessageCreatingReply + 22
    frame #7: 0x270378ac CoreMedia`FigXPCSendStdSetPropertyMessage + 96
    frame #8: 0x2b63923a Celestial`captureSourceRemote_SetProperty + 110
    frame #9: 0x253a225a AVFoundation`__66-[AVCaptureFigVideoDevice _setFigCaptureSourceProperty:withValue:]_block_invoke + 54
    frame #10: 0x016201d8 libdispatch.dylib`_dispatch_barrier_sync_f_invoke + 96
    frame #11: 0x253a2210 AVFoundation`-[AVCaptureFigVideoDevice _setFigCaptureSourceProperty:withValue:] + 112
    frame #12: 0x2539ffc0 AVFoundation`__46-[AVCaptureFigVideoDevice setVideoZoomFactor:]_block_invoke + 152
    frame #13: 0x016189c6 libdispatch.dylib`_dispatch_client_callout + 22
    frame #14: 0x016201d8 libdispatch.dylib`_dispatch_barrier_sync_f_invoke + 96
    frame #15: 0x2539fcfa AVFoundation`-[AVCaptureFigVideoDevice setVideoZoomFactor:] + 278
    frame #16: 0x25395b68 AVFoundation`-[AVCaptureFigVideoDevice setActiveFormat:] + 592
    frame #17: 0x274f529e Foundation`_NSSetObjectValueAndNotify + 94
    frame #18: 0x274e2ef8 Foundation`-[NSObject(NSKeyValueCoding) setValue:forKey:] + 204
    frame #19: 0x00046faa SimpleDemo`-[GstAVFVideoSrcImpl setDeviceCaps:](self=<unavailable>, info=<unavailable>, _cmd=<unavailable>) + 526 at avfvideosrc.m:429
    frame #20: 0x00047e2c SimpleDemo`__30-[GstAVFVideoSrcImpl setCaps:]_block_invoke(.block_descriptor=<unavailable>) + 196 at avfvideosrc.m:614
    frame #21: 0x016201d8 libdispatch.dylib`_dispatch_barrier_sync_f_invoke + 96
    frame #22: 0x00047d5c SimpleDemo`-[GstAVFVideoSrcImpl setCaps:](self=<unavailable>, _cmd=<unavailable>, new_caps=0x159c4968) + 228 at avfvideosrc.m:596
    frame #23: 0x0004934c SimpleDemo`gst_avf_video_src_set_caps(basesrc=<unavailable>, caps=<unavailable>) + 76 at avfvideosrc.m:1200
    frame #24: 0x0030b838 SimpleDemo`gst_base_src_set_caps(src=0x15969098, caps=0x159c4968) + 76 at gstbasesrc.c:922
    frame #25: 0x0030fdfa SimpleDemo`gst_base_src_default_negotiate(basesrc=0x15969098) + 338 at gstbasesrc.c:3226
    frame #26: 0x0030c82c SimpleDemo`gst_base_src_loop [inlined] gst_base_src_negotiate + 36 at gstbasesrc.c:3266
    frame #27: 0x0030c808 SimpleDemo`gst_base_src_loop(pad=0x15a08150) + 128 at gstbasesrc.c:2693
    frame #28: 0x00372120 SimpleDemo`gst_task_func(task=0x161d10f8) + 276 at gsttask.c:331
    frame #29: 0x0023ca40 SimpleDemo`g_thread_pool_thread_proxy(data=<unavailable>) + 120 at gthreadpool.c:307
    frame #30: 0x0023fbf6 SimpleDemo`g_thread_proxy(data=0x159f63d8) + 78 at gthread.c:764
    frame #31: 0x3475ee92 libsystem_pthread.dylib`_pthread_body + 138
    frame #32: 0x3475ee06 libsystem_pthread.dylib`_pthread_start + 118
(lldb) 
```

**Comment by superdump** [comment]
Try continuing past the SIGTRAP with `c` and then enter. I think G_DEBUG=fatal-warnings should trigger a SIGABRT but I'm not certain at this moment.

**Comment by sdroege** [comment]
Thanks, that probably tells me later all I need to know :)

**Comment by sdroege** [comment]
It triggers a trap like this on osx and iOS when running in a debugger. Outside it triggers abort

**Comment by superdump** [comment]
Ah interesting. Ignore what I said then. :smile:

**Comment by sdroege** [comment]
That's btw why you can continue at all in a debugger when a warning happens. If it was always an abort, that wouldn't be possible. Confused me for a while

**Comment by sdroege** [comment]
@stefanalund was there something output on the terminal before the trap? That backtrace looks like it's a different problem, coming from somewhere inside AVFoundation.

**Comment by stefanalund** [comment]
Only this:

```
** Message: Loaded namespace: GLib
** Message: Loaded namespace: GObject
** Message: Loaded namespace: Gio
** Message: Loaded namespace: GIRepository
** Message: Loaded namespace: Owr
WARNING: no real random source present!
** Message: ready

(<unknown>:6250): GStreamer-CRITICAL **: gst_query_set_latency: assertion 'GST_CLOCK_TIME_IS_VALID (min_latency)' failed
```

**Comment by stefanalund** [comment]
And yes @superdump, I can continue.

**Comment by sdroege** [comment]
Weird, it seems like the trap is delayed for some time then and does not happen immediately. Not very useful for debugging, but enough for us... at least we know that it's in avfvideosrc. I'll try to look again to find where this can possibly go wrong tomorrow :smile:

**Comment by sdroege** [comment]
According to the line numbers this is the version without my fix. I fixed it in 84ab11afdbfd87bf1aa916cc7803163536513339 (of gst-plugins-bad) and the version before that had exactly the line numbers from the backtrace.
