### ISSUE TITLE
Failed to build openwebrtc on os x

### ISSUE THREAD

**Issue by ksenks** [EricssonResearch/openwebrtc#202]
The boostrapping and building dependences stages finished well, but the building stage failed:

./build.sh -Cbr osx

 CC       libopenwebrtc_bridge_la-owr_bridge.lo
  CCLD     libopenwebrtc_bridge.la
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
  CC       daemon.o
  CCLD     openwebrtc-daemon
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
Undefined symbols for architecture x86_64:
  "_gst_plugin_nice_register", referenced from:
      _owr_init in libopenwebrtc.a(owr.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [openwebrtc-daemon] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Failed building....

Could you please help with that?

**Comment by tang85718** [comment]
me too

**Comment by j0sh** [comment]
Happening here as well.

**Comment by sdroege** [comment]
This should've been fixed with https://github.com/EricssonResearch/openwebrtc-build-scripts/commit/9fe9423288aa857de4d8d7827575435b835e5613 and now with https://github.com/EricssonResearch/openwebrtc/commit/e3cb813a8b56da712e551625d765c2c7ac47483c should also be inside the scripts submodule finally.

You need to rebuild libnice for this to work.

**Comment by j0sh** [comment]
Doesn't seem to have worked, still failing with the same error.

Removed all instances of libnice.a, updated webrtc and scripts to current tip, then rebuilt libnice, with --enable-static-plugins appearing in config.log as expected. No dice.

**Comment by sdroege** [comment]
Did you deploy the dependencies again after rebuilding libnice?

**Comment by j0sh** [comment]
Yes.

**Comment by j0sh** [comment]
So, ./deploy_deps.sh only copies an existing tarball from the dependencies dir, it does not create a new one. After re-building libnice, re-run ./create-file-release.sh, then run ./deploy-deps. From there, OWR seems to compile OK.

**Comment by ksenks** [comment]
I re-builded all the things from the scratch and still got the same error.
