### ISSUE TITLE
Ubuntu 1404 build failure

### ISSUE THREAD

**Issue by weixingsun** [EricssonResearch/openwebrtc#266]
Hi there, 

I am facing a build issue on my own ubuntu 1404 desktop, 
there is nothing special when compiling the dependencies, but when I turn to $OPENWEBRTC/build.sh -Cbr linux to make the final lib, the error as follows blocked me:
... ...
  GISCAN Owr-0.1.gir
./.libs/libopenwebrtc.so: undefined reference to `gst_plugin_dtls_register'
collect2: error: ld returned 1 exit status
linking of temporary binary failed: Command '['/bin/bash', '../libtool', '--mode=link', '--tag=CC', '--silent', 'gcc', '-o', '/home/sun/openwebrtc/openwebrtc/build/x86_64-unknown-linux/owr/tmp-introspectCowNPl/Owr-0.1', '-export-dynamic', '-fPIC', '-I/home/sun/openwebrtc/openwebrtc/openwebrtc-deps-x86_64-linux/include', '-I/home/sun/openwebrtc/openwebrtc/framework', '-L/home/sun/openwebrtc/openwebrtc/openwebrtc-deps-x86_64-linux/lib', '-L/home/sun/openwebrtc/openwebrtc/openwebrtc-deps-x86_64-linux/lib/gstreamer-1.0', '-L/home/sun/openwebrtc/openwebrtc/openwebrtc-deps-x86_64-linux/lib', '/home/sun/openwebrtc/openwebrtc/build/x86_64-unknown-linux/owr/tmp-introspectCowNPl/Owr-0.1.o', '-L.', 'libopenwebrtc.la', '-L/home/sun/.openwebrtc/lib', '-lgio-2.0', '-lgobject-2.0', '-Wl,--export-dynamic', '-lgmodule-2.0', '-pthread', '-lglib-2.0', '-lintl']' returned non-zero exit status 1
make[3]: *** [Owr-0.1.gir] Error 1
make[3]: Leaving directory `/home/sun/openwebrtc/openwebrtc/build/x86_64-unknown-linux/owr'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/sun/openwebrtc/openwebrtc/build/x86_64-unknown-linux/owr'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/sun/openwebrtc/openwebrtc/build/x86_64-unknown-linux'
make: *** [all] Error 2
Failed building....

I found out that there was a commit recently which related to gst_plugin for replacing erdtls by dtls :+:
- GST_PLUGIN_STATIC_REGISTER(erdtls);
+ GST_PLUGIN_STATIC_REGISTER(dtls);

I am wondering if any other libraries or configurations needed for this change, or shall we temporaryly roll back to erdtls one?

Your professional suggestions will be highly appreciated.

Regards,
Weixing

**Comment by nirbheek** [comment]
You will need to rebuild (which will update) the gst-plugins-bad dependency. This should fix the build error.

**Comment by weixingsun** [comment]
Hi Nirbheek,

Thanks for your reply, I downloaded the source code last night, and updated source just now, but unforturnately this issue still occurred when I build the 
are you using the following options for your environment? 
./build-gst-plugins-bad.sh -Cbr linux
and what configuration should be used for eliminate the undefined reference error for 'gst_plugin_dtls_register' ? do I need to install more libs or settings for environmental variables ?

I didn't change anything in the script of build-gst-plugins-bad.sh: 
            ${home}/$BUILD_DIR/configure \
                --prefix=${installdir} \
                --host=${target_triple} \
                --disable-eglgles \
                --disable-asfmux \
                --disable-freeverb \
                --disable-decklink \
                --disable-mpegtsmux \
                --disable-mpegpsmux \
                --disable-yadif \
                --disable-fatal-warnings \
                --enable-static \
                --disable-shared \
                --enable-static-plugins \
                --disable-introspection \
                --enable-gobject-cast-checks=no ${extra_configure_flags} \
                || exit 1
Regards,
Weixing

**Comment by nirbheek** [comment]
Sorry, I misunderstood how the build scripts work (I don't actually use it myself; I use [Cerbero](https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC-with-Cerbero) to build OpenWebRTC). build-gst-plugins-bad.sh needs to be updated to the latest version of upstream git.

You will likely have better luck building everything with Cerbero, to be honest. See https://github.com/EricssonResearch/openwebrtc/issues/222 :)

**Comment by superdump** [comment]
As @nirbheek mentioned, we're fully focused on moving to the cerbero build system to get everything building there and even to make a first official release with downloadable binaries so that people who are most interested in just trying out OpenWebRTC can get going as quickly as possible.

**Comment by weixingsun** [comment]
Hi Superdump,

Thank you for introducing me the cerbero, I am switching to work on it now. 
But I got an issue when building glib component: saying that my pkg-config is too old, but I have double confirmed pkg-config is installed and upgraded to 0.28 revision. 
I checked the glib dir on ~/cerbero/sources/linux_x86_64/glib-2.42.2, 
the configure script shown that the version is required as _pkg_min_version=0.16, I think my 0.28 is good enough, right ? 
Any idea about it ?

checking for zlib.h... yes
checking for LIBFFI... no
configure: error: in `/home/sun/cerbero/sources/linux_x86_64/glib-2.42.2':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

Alternatively, you may set the environment variables LIBFFI_CFLAGS
and LIBFFI_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

To get pkg-config, see <http://pkg-config.freedesktop.org/>.
See `config.log' for more details
Running command 'sh autogen.sh --prefix /home/sun/cerbero/dist/linux_x86_64 --libdir /home/sun/cerbero/dist/linux_x86_64/lib  --enable-static --disable-selinux --disable-maintainer-mode  --disable-silent-rules  --enable-introspection '

**Comment by weixingsun** [comment]
Hello team,

I am glad to moving forward on my build with cerbero branch, previous issue is due to no bootstrap compiled .
But in the step 35/36 of ./cerbero-uninstalled package openwebrtc, there is a patch:113 could not be proceeded. 
Does anyone meet this issue before ?
-----------------------------------------------
[(35/36) openwebrtc -> extract ]
HEAD is now at 977a564 Update ROADMAP.md
fatal: A branch named 'cerbero_build' already exists.
Already on 'cerbero_build'
HEAD is now at 977a564 Update ROADMAP.md
Cloning into '.'...
done.
Applying: Owr: Use videoconvert instead of ercolorspace on Android
Applying: Fix build on Android and iOS when not using build.sh
/home/sun/cerbero/sources/linux_x86_64/openwebrtc-0.1/.git/rebase-apply/patch:113: trailing whitespace.
  dnl The GNU C++ STL is needed for JNI. This pkg-config file is
error: patch failed: configure.ac:115
error: configure.ac: patch does not apply
Patch failed at 0001 Fix build on Android and iOS when not using build.sh
The copy of the patch that failed is found in:
   /home/sun/cerbero/sources/linux_x86_64/openwebrtc-0.1/.git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Running command 'rm -rf /home/sun/cerbero/sources/linux_x86_64/openwebrtc-0.1'
Running command 'git reset --hard origin/master'
Running command 'git branch cerbero_build'
Running command 'git checkout cerbero_build'
Running command 'git reset --hard origin/master'
Running command 'git clone /home/sun/cerbero/sources/local/openwebrtc -s -b cerbero_build .'
Running command 'git am --ignore-whitespace /home/sun/openwebrtc/cerbero/cerbero/recipes/openwebrtc/0001-Owr-Use-videoconvert-instead-of-ercolorspace-on-Andr.patch'
Running command 'git am --ignore-whitespace /home/sun/openwebrtc/cerbero/cerbero/recipes/openwebrtc/0002-Fix-build-on-Android-and-iOS-when-not-using-build.sh.patch'

Recipe 'openwebrtc' failed at the build step 'extract' ....

**Comment by nirbheek** [comment]
@weixingsun That problem should be fixed now, thanks! Could you try again? (Also, in future, please open new issues for unrelated/new problems!)

**Comment by superdump** [comment]
https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC
