### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by stefhak** [EricssonResearch/openwebrtc#279]
$ ./cerbero-uninstalled build openwebrtc
fails on the last recipe:
"[(34/34) openwebrtc -> fetch ]
-----> Step done
[(34/34) openwebrtc -> extract ]
HEAD is now at 8f64b74 replace gst_object_default_deep_notify with a less verbose _owr_deep_notify that uses log level info
fatal: A branch named 'cerbero_build' already exists.
Already on 'cerbero_build'
HEAD is now at 8f64b74 replace gst_object_default_deep_notify with a less verbose _owr_deep_notify that uses log level info
Cloning into '.'...
done.
Applying: Owr: Use videoconvert instead of ercolorspace on Android
Applying: Fix build on Android and iOS when not using build.sh
error: patch failed: bindings/java/Makefile.am:21
error: bindings/java/Makefile.am: patch does not apply
error: patch failed: configure.ac:104
error: configure.ac: patch does not apply
error: patch failed: owr/Makefile.am:7
error: owr/Makefile.am: patch does not apply
Patch failed at 0001 Fix build on Android and iOS when not using build.sh
The copy of the patch that failed is found in:
   /Users/eplhak/cerbero/sources/darwin_x86_64/openwebrtc-0.1/.git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Running command 'rm -rf /Users/eplhak/cerbero/sources/darwin_x86_64/openwebrtc-0.1'
Running command 'git reset --hard origin/master'
Running command 'git branch cerbero_build'
Running command 'git checkout cerbero_build'
Running command 'git reset --hard origin/master'
Running command 'git clone /Users/eplhak/cerbero/sources/local/openwebrtc -s -b cerbero_build .'
Running command 'git am --ignore-whitespace /Users/eplhak/cerbero/recipes/openwebrtc/0001-Owr-Use-videoconvert-instead-of-ercolorspace-on-Andr.patch'
Running command 'git am --ignore-whitespace /Users/eplhak/cerbero/recipes/openwebrtc/0002-Fix-build-on-Android-and-iOS-when-not-using-build.sh.patch'

Recipe 'openwebrtc' failed at the build step 'extract'"

**Comment by superdump** [comment]
This should be fixed already. We're doing some final bits and pieces to move some patches from cerbero into openwebrtc master and then remove the old build scripts build method. Follow this: https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC-with-Cerbero#updating

**Comment by stefhak** [comment]
I followed that guide ... but it was several hours ago so it is probably fixed now. I'll do it again soon, and if it works then I'll just close this issue.

**Comment by ijsf** [comment]
I am having the same issue with current Cerbero master (commit d79ba9d750bd17d01b0993b55b264b4b24c377c2) and can verify this is not fixed by doing a `git pull --rebase`.

**Comment by ijsf** [comment]
Just noticed you guys have silently switched repositories from https://github.com/nirbheek/cerbero/commits/openwebrtc to https://github.com/EricssonResearch/cerbero/commits/master..

Pulling from the latter will probably fix this issue.

**Comment by superdump** [comment]
https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC

**Comment by stefhak** [comment]
Works now (after switching to the Ericsson cerbero and rebuilding).
