### ISSUE TITLE
libffi armv7/armv7s crashing

### ISSUE THREAD

**Issue by superdump** [EricssonResearch/openwebrtc#385]
When using Bowser on armv7/armv7s, the bridge thread segfaults during startup: https://gist.github.com/superdump/996d8550beaf491c99e3

I have tested arm64 and it is only armv7/armv7s that crashes. This basically means that Bowser is currently not usable on devices using CPUs before the A7. That is, devices older than (and including) iPhone 5 / 5C, iPad 4, iPad Mini 2.

**Comment by plindseth** [comment]
I've been trying get Bowser to work on a fourth-generation iPad for a few days (didn't see the above until now), but unfortunately I guess this post definitively makes that impossible. Are there any plans to add support for non-arm64 devices at some point in the future?

**Comment by superdump** [comment]
Yes. I am slowly working through testing different versions of libffi to try to find something that works so that we can build one version for iOS armv7/armv7s and another for arm64 until this is fixed for all.

**Comment by jokerttu** [comment]
Seem like same issue (armv7 + libffi) has been under discussion at here: https://bugs.python.org/issue23670

**Comment by superdump** [comment]
@jokerttu - what exactly did you do to get it working with that commit? I tried the following:

```diff
@@ -46,6 +46,9 @@ class Recipe(recipe.Recipe):
                 dir = 'aarch64-apple-darwin*'
                 arch = 'arm64'
             elif Architecture.is_arm(self.config.target_arch):
+                # armv7 and armv7s
+                self.commit = '20562ac0427c3578250d04c6e34fb0127d4551cf'
+                self.patches = ['libffi/0001-libffi-Don-t-be-smart-about-toolexeclibdir.patch']
                 dir = 'arm-apple-darwin*'
                 arch = 'arm'
```

But I still get the same crash here. What exactly did you build? Can you make a patch?

**Comment by jokerttu** [comment]
@superdump - I have exactly same changes than above; same commit and same patches. But for some reason it did not re-compile it before I changed the version as well.
(I am not so familiar with cerbero build environment, so it might be that I should have cleaned the previous build/cache first).

-    version = '3.99999'
+    version = '3.2.1'

After this it started to work on iPad2 which runs over Cortex-A9 (ARMv7-A), and this is only devise I have been working with at the moment; so it might be that this commit does not fix ARMv7s builds, only ARMv7.

**Comment by superdump** [comment]
@jokerttu - I have tried with the above changes, plus a patch to fake 3.2.1 as 3.99999 on armv7 / armv7s and I get exactly the same crash as noted in the first post in this issue:

```
2015-06-12 16:54:09.019 Bowser[503:124432] BowserViewController viewDidLoad
2015-06-12 16:54:09.390 Bowser[503:124470] OWR bridge starting...
** Message: Loaded namespace: GLib
** Message: Loaded namespace: GObject
** Message: Loaded namespace: Gio
** Message: Loaded namespace: GIRepository
** Message: Loaded namespace: Owr
0:00:00.007415000   503 0x152b1008 WARN            GST_REGISTRY gstregistry.c:1836:gboolean gst_update_registry(): registry update failed: registry disabled
** Message: ready
2015-06-12 16:54:10.483 Bowser[503:124470] OWR bridge started
2015-06-12 16:54:10.980 Bowser[503:124432] webViewDidStartLoading...
2015-06-12 16:54:10.981 Bowser[503:124432] creating timer
2015-06-12 16:54:11.617 Bowser[503:124432] injecting bootstrap script
(lldb) bt
* thread #15: tid = 0x1e655, 0x198ac190, name = 'owr-bridge-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x198ac190)
    frame #0: 0x198ac190
  * frame #1: 0x0024578c Bowser`ffi_closure_inner_SYSV(cif=0x0059f451, fun=<unavailable>, user_data=<unavailable>, frame=<unavailable>) + 128 at ffi.c:511
```

**Comment by ageekhere** [comment]
Any updates on a fix for this? and when will it be updated on itunes?

**Comment by superdump** [comment]
A possible fix was pushed to the Frida fork of libffi yesterday so I'll be testing that today.

**Comment by ageekhere** [comment]
How did the testing go, was it able to fix the issue?

**Comment by superdump** [comment]
Unfortunately not. There is something broken with a closure on armv7.

**Comment by superdump** [comment]
Due to a bug in cerbero, I was building using the iOS 8.3 SDK. I will try some variants again with the iOS 8.4 SDK when I get time to see if they work.

**Comment by ageekhere** [comment]
did 0.4 have this problem? I remember testing Bowser on the iphone 5 before 0.5 came out and it did not have a problem. Maybe we need to revert back to a working version until the current issue is fixed?

**Comment by superdump** [comment]
0.4 doesn't support 64-bit and so would no longer be allowed on the App Store I think.

**Comment by superdump** [comment]
I have been told that an armv7 version of libffi can be built using the old build scripts we had. That could help narrowing things down.

**Comment by bamboolsu** [comment]
@superdump and related experts:

For this issue, have we fixed it now? where can we get the fixed code? thanks.

Another question:
  For version of 0.3.1, Bowser cannot support IPhone 6s, and Iphone 6 with IOS9.  If we want to use this bowser, how can we do it? are there any plan for handling the problem for latest IOS 9?

**Comment by superdump** [comment]
At the moment it doesn't look like upstream libffi is going to address the problem so we may have to go 64-bit only for the next Bowser release. iOS 9 would of course be supported in that and I think it is already fixed to work with iOS 9 in the bowser repository.

**Comment by stefanalund** [comment]
Maybe, maybe not: https://github.com/EricssonResearch/bowser/issues/60

**Comment by bamboolsu** [comment]
Hi, @jokerttu 

Based on you info,   build OpenWebRTC with old libffi ('20562ac0427c3578250d04c6e34fb0127d4551cf'), I have build armv7 and armv7s, and run bowser on Iphone 5, Iphone 5 still crash!

I have done the following:
1, clean all ~/cerbero/*.cache
2, modify the following in the file of recipes/libffi.recipe  like @superdump  has done.
+                # armv7 and armv7s
+                self.commit = '20562ac0427c3578250d04c6e34fb0127d4551cf'
+                self.patches = ['libffi/0001-libffi-Don-t-be-smart-about-toolexeclibdir.patch']

2, Bootstrap/rebuild mac os host and iOS armv7/armv7s.
3, Using my build armv7 or armv7s in the project of https://github.com/EricssonResearch/bowser/tree/master/bowser-ios.   run it on my Iphone 5 which will use the default test page of http://demo.openwebrtc.org:38080/.   the the bowser crash and exit.

Then @jokerttu, how can you run the bowser on your Iphone5 or other armv7 on you device? can you give some clue, thanks! :)

**Comment by stefanalund** [comment]
This PR seems to fixa this issue, at least on iPhone 6s: https://github.com/EricssonResearch/cerbero/pull/38

**Comment by stefanalund** [comment]
Confirmed that Bowser now also works on iPhone 5 (32-bit)!

**Comment by superdump** [comment]
This should be fixed in cerbero master and so should also be fixed in the next releases of OpenWebRTC and Bowser! \o/

**Comment by tristan-k** [comment]
do I have to sideload bower or will the new version soon released on the app store?

**Comment by stefanalund** [comment]
@tristan-k we will be releasing this fix as part of a bigger update. You can follow and test it in advance here https://github.com/EricssonResearch/bowser/pull/61#issuecomment-152708380
