### ISSUE TITLE
Openwebrtc issue 

### ISSUE THREAD

**Issue by skimsafe1** [EricssonResearch/openwebrtc#692]
@sdroege
@superdump
@pererikb

To whom it may concern 

Hello, My name is San Kim. 
I am Vice President of Joeun Safe. We are running a home CCTV called Ouibot, which uses Openwebrtc. 
Our S/W developers are matescorp. You may know the ID better as 'nakyup' (alex.park@matescorp)

Today, I am writing this post to make a desperate request. 
Our company has had a serious refund issue since android nougat (7.0) released. 
Because the call cannot be connected peer to peer, we cannot sell the products. Furthermore, since the issue has lasted continouslely, we are refunding the devices. Our developers have consulted on this issue with ericsson openwebrtc team for last 4~5 months. 

We are very desperate and urgent. Could you spare some time to talk about this issue with your team?
I will fly to your working venue asap. 
I want to explain how desperate we are. And also I want to talk on the issue such as when this issue will be solved, what is more needed to get the problem solved as such. 

Could please spare some time for us? And please let us know how I can meet you for talking about this issue. 

You can email me directly to skim@safe1.co.kr 
I will be looking foward to your reply.

**Comment by sdroege** [comment]
I'm not working on OpenWebRTC anymore, but there are various consultancy companies that could provide you with support for anything GStreamer related and could help here.

**Comment by DblA** [comment]
Android 7 has an issue with dynamic linking against non-NDK libraries. This has prevented me from updating my devices, as I don't know how to fix building the OpenWebRTC to be compliant yet.

 There's an issue open about this already: #672

**Comment by pererikb** [comment]
This should fix that issue:
https://github.com/pererikb/openwebrtc-gst-plugins/commits/android_dlopen
https://github.com/pererikb/openwebrtc/commits/android_dlopen

**Comment by DblA** [comment]
Applied the patches but still no go on Android 7 (LG Nexus 5X/Android 7.1.2).

Seeing some errors:
E/OWR: jniutils-N: jni/jni_utils.c jniutils_get_created_vm ERROR: get created Java VM failed
E/gstandroidvideosrc: jni/gst_android_video_source.c ERROR: init videocapturedevice module (VCD) failed

crash after:
ERROR:owr_local_media_source.c:724:owr_local_media_source_request_source: assertion failed: (source)

Same code works on Android 6 (Nvidia Shield K1/6.0.1).

**Comment by sdroege** [comment]
That might very well be https://bugzilla.gnome.org/show_bug.cgi?id=785406

**Comment by DblA** [comment]
I can confirm that patches from @pererikb fix issues with Android 7.

(Problem I had earlier was caused by not changing the openwebrtc-gst-plugins-static.recipe on cerbero, which resulted in compiling openwebrtc with unpatched files.)

**Comment by skimsafe1** [comment]
Dear All 
Thanx. We finally got the problem solved. We sincerely appreciate your supports.
